services:

  database:
    image: postgres
    hostname: database
    volumes:
      - database:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis
    ports:
      - "6379:6379"

#  celery:
#    build: .
#    command: celery -A app.celery worker --loglevel=info
#    depends_on:
#      - redis


volumes:
  database:
