services:

  database:
    image: postgis/postgis:17-3.5
    hostname: database
    volumes:
      - database-volume:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - env.docker
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis/redis-stack
    ports:
      - "127.0.0.1:6379:6379"

  celery_application:
    build: .
    command: celery --app ccrew.celery_app worker --loglevel DEBUG
    depends_on:
      database:
        condition: service_healthy
        # restart: true
      redis:
        condition: service_started
    env_file:
        - env.docker

  flask_application:
    build: .
    # command: python -m flask --app ccrew.flask_app run
    depends_on:
      database:
        condition: service_healthy
        # restart: true
      redis:
        condition: service_started
    env_file:
        - env.docker
    ports:
      - "127.0.0.1:8050:5000"

volumes:
  database-volume:
